### ISSUE TITLE
Review 任务

### ISSUE THREAD

**Issue by QC-L** [vitejs/docs-cn#78]
> 本次认领仅限之前参加过 vite 文档翻译的小伙伴，具体原因请参考 #77

由于文档内容有限，建议一人一篇。

**在 review 过程中，请务必认真对待，逐行逐字对比**。因为最近同步过程中，发现了很多错漏内容。

格式规范请务必遵循 [wiki](https://github.com/vitejs/docs-cn/wiki/%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83)，减少不必要的返工。

review 后内容，请提交到 dev 分支。

## 任务认领说明

从 Todo List 中选取未被人领取过的文章：

未被领取过：

* [ ] guide/index

领取过：

* [ ] guide/index (@QC-L)

领取过，已完成：

* [x] guide/index (@QC-L) #1

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/index | 开始 | @QC-L | 2021.04.13 - 2021.04.13
```

示例效果：

| Section | Title         | 译者  | 完成时间                |
| ------- | ------------- | ----- | ----------------------- |
| guide/index | 开始 | @QC-L | 2021.04.13 - 2021.04.13 |

## 任务认领列表

Todo List:

- [x] [blog](https://github.com/vitejs/docs-cn/blob/dev/blog/)
  - [x] [announcing-vite2](https://github.com/vitejs/docs-cn/blob/dev/blog/announcing-vite2.md) (@G233) #89 
- [x] [config](https://github.com/vitejs/docs-cn/blob/dev/config/)
  - [x] [index](https://github.com/vitejs/docs-cn/blob/dev/config/index.md) (@wjq990112) #80 
- [x] [guide](https://github.com/vitejs/docs-cn/blob/dev/guide/)
  - [x] [api-hmr](https://github.com/vitejs/docs-cn/blob/dev/guide/api-hmr.md)  (@ShenQingchuan) #110 
  - [x] [api-javascript](https://github.com/vitejs/docs-cn/blob/dev/guide/api-javascript.md)  (@ShenQingchuan)
  - [x] [api-plugin](https://github.com/vitejs/docs-cn/blob/dev/guide/api-plugin.md)  (@ShenQingchuan) #111 
  - [x] [assets](https://github.com/vitejs/docs-cn/blob/dev/guide/assets.md)  (@ShenQingchuan)  #112  
  - [x] [backend-integration](https://github.com/vitejs/docs-cn/blob/dev/guide/backend-integration.md)  (@ShenQingchuan)  #113 
  - [x] [build](https://github.com/vitejs/docs-cn/blob/dev/guide/build.md) (@QC-L) #92 
  - [x] [comparisons](https://github.com/vitejs/docs-cn/blob/dev/guide/comparisons.md)  (@ShenQingchuan)  #114 
  - [x] [dep-pre-bundling](https://github.com/vitejs/docs-cn/blob/dev/guide/dep-pre-bundling.md)  (@ShenQingchuan)  #116 
  - [x] [env-and-mode](https://github.com/vitejs/docs-cn/blob/dev/guide/env-and-mode.md) (@ATQQ) #99 
  - [x] [features](https://github.com/vitejs/docs-cn/blob/dev/guide/features.md) (@Ivocin) #90 
  - [x] [index](https://github.com/vitejs/docs-cn/blob/dev/guide/index.md)  (@ShenQingchuan)  #117
  - [x] [migration](https://github.com/vitejs/docs-cn/blob/dev/guide/migration.md) (@QC-L) #119
  - [x] [ssr](https://github.com/vitejs/docs-cn/blob/dev/guide/ssr.md) (@ShenQingchuan) #104
  - [x] [static-deploy](https://github.com/vitejs/docs-cn/blob/dev/guide/static-deploy.md) (@Wzb3422)  #91 
  - [x] [using-plugins](https://github.com/vitejs/docs-cn/blob/dev/guide/using-plugins.md) (@Ivocin) #120
  - [x] [why](https://github.com/vitejs/docs-cn/blob/dev/guide/why.md) (@KnowsCount) #86 
- [x] [plugins](https://github.com/vitejs/docs-cn/blob/dev/plugins/)
  - [x] [index](https://github.com/vitejs/docs-cn/blob/dev/plugins/index.md) (@QC-L)

**Comment by wjq990112** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
config/index | Vite 配置 | @wjq990112  | 2021.04.13 - 2021.04.16

**Comment by Wzb3422** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/static-deploy | 部署静态站点 | @Wzb3422  | 2021.04.13 - 2021.04.16

**Comment by KnowsCount** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/why | 为什么选 Vite | @KnowsCount | 2021.04.13 - 2021.04.16

**Comment by QC-L** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/build | 开始 | @QC-L | 2021.04.13 - 2021.04.16

**Comment by Ivocin** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/features | 功能 | @Ivocin  | 2021.04.13 - 2021.04.18

**Comment by G233** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
blog/announcing-vite2 | Vite 2.0 发布了 | @G233 | 2021.04.13 - 2021.04.18

**Comment by ATQQ** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/env-and-mode | 环境变量与模式 | @ATQQ | 2021.05.01 - 2021.05.05

**Comment by ShenQingchuan** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/ssr | 服务端渲染 | @ShenQingchuan | 2021.05.09 - 2021.05.10

**Comment by QC-L** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
plugins/index | 插件 | @QC-L | 2021.05.13 - 2021.05.13

**Comment by ShenQingchuan** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/api-javascript | JavaScript API | @ShenQingchuan | 2021.05.15 - 2021.05.16

**Comment by ShenQingchuan** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/api-plugin| 插件 API | @ShenQingchuan | 2021.05.15 - 2021.05.16

**Comment by ShenQingchuan** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/backend-integration | 后端集成 | @ShenQingchuan | 2021.05.15 - 2021.05.16

**Comment by ShenQingchuan** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/comparisons | 比较 | @ShenQingchuan | 2021.05.15 - 2021.05.16

**Comment by ShenQingchuan** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/dep-pre-bundling | 依赖预构建 | @ShenQingchuan | 2021.05.17 - 2021.05.18

**Comment by ShenQingchuan** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/index | 开始 | @ShenQingchuan | 2021.05.17 - 2021.05.18

**Comment by Ivocin** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/using-plugins | 使用插件 | @Ivocin  | 2021.05.18 - 2021.05.20

**Comment by QC-L** [comment]
Done! 感谢各位
